version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: weekly
      open-pull-requests-limit: 1
      groups:
        actions-pages:
          patterns:
          - "actions/configure-pages"
          - "actions/deploy-pages"
          - "actions/upload-pages-artifact"
        actions-patch:
          patterns:
          - "*"
          update-types:
          - "patch"
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: monthly
      open-pull-requests-limit: 1
      groups:
        docs:
          patterns:
          - "*"
