name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version-file: '.nvmrc'
          cache: "yarn"
      - run: yarn
      - name: Build
        run: yarn docs:build
      - uses: actions/configure-pages@v3.0.6
      - uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: .vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2.0.5
